
export const EMAILJS_TEMPLATES = {
    CONTACT_US: process.env.NEXT_PUBLIC_EMAILJS_CONTACT_TEMPLATE_ID || '',
    SUBSCRIPTION_RECEIPT: process.env.NEXT_PUBLIC_EMAILJS_RECEIPT_TEMPLATE_ID || '',
    USER_INVITATION: process.env.NEXT_PUBLIC_EMAILJS_INVITE_TEMPLATE_ID || '',
};
