'use client';

import * as React from 'react';
import { useRouter } from 'next/navigation';
import { useChat } from '@ai-sdk/react';
import { DefaultChatTransport, isToolUIPart } from 'ai';
import { Bot, X, Sparkles, Loader2, User, Mic, ArrowUp, Maximize2, Minimize2, Trash2, Square, ExternalLink, Zap } from 'lucide-react';
import { getAuth } from 'firebase/auth';
import { doc, onSnapshot } from 'firebase/firestore';
import { useUser, useFirestore } from '@/firebase';
import { apiBase } from '@/lib/platform';
import { Markdown } from '@/components/ai-insights/markdown';
import { ToolResult } from '@/components/ai-insights/tool-renderer';
import { validateProposal, buildSaleFromProposal } from '@/components/ai-insights/proposal-guard';
import { trackFeature } from '@/lib/product-telemetry';
import { usePOS } from '@/context/pos-context';
import { useToast } from '@/hooks/use-toast';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { AnimatePresence, motion } from 'framer-motion';

// Helper to extract text from a message (compatible with AI SDK v5+ parts)
function textOf(message: any): string {
  if (!message) return '';
  if (typeof message.content === 'string') return message.content;
  if (!Array.isArray(message.parts)) return '';
  return message.parts
    .filter((p: any) => p?.type === 'text' && typeof p.text === 'string')
    .map((p: any) => p.text)
    .join(' ');
}

interface ZenAIWidgetProps {
  isOpen: boolean;
  onClose: () => void;
  dictationTrigger?: number;
}

export default function ZenAIWidget({ isOpen, onClose, dictationTrigger = 0 }: ZenAIWidgetProps) {
  const router = useRouter();
  const { toast } = useToast();
  const { user } = useUser();
  const firestore = useFirestore();
  const { addToQueue, products, customers, currentUserProfile } = usePOS();

  const businessId = currentUserProfile?.businessId || (user as any)?.businessId || '';
  const [businessData, setBusinessData] = React.useState<any>(null);
  const [proposalStatuses, setProposalStatuses] = React.useState<Record<string, 'APPROVED' | 'REJECTED'>>({});
  
  // Track credits exhaustion to display upgrade card
  const [creditsExhausted, setCreditsExhausted] = React.useState<{ plan: string; monthlyLimit: number; errorText?: string } | null>(null);

  // Dynamic expand / collapse state
  const [isExpanded, setIsExpanded] = React.useState(false);

  const [sessionId, setSessionId] = React.useState(() => `session_widget_${Date.now()}`);
  const scrollAreaRef = React.useRef<HTMLDivElement>(null);
  const inputRef = React.useRef<HTMLInputElement>(null);

  // Fetch business instance data for proposal actions
  React.useEffect(() => {
    if (!businessId || !firestore) return;
    const unsubscribe = onSnapshot(doc(firestore, 'businessInstances', businessId), (docSnap) => {
      if (docSnap.exists()) {
        setBusinessData(docSnap.data());
      }
    });
    return () => unsubscribe();
  }, [businessId, firestore]);

  // Audio dictation state
  const [isListening, setIsListening] = React.useState(false);
  const recognitionRef = React.useRef<any>(null);

  // Setup the transport for the chat API
  const transport = React.useMemo(() => new DefaultChatTransport({
    api: apiBase() + '/api/chat',
    prepareSendMessagesRequest: async ({ messages, body }) => {
      const token = await getAuth().currentUser?.getIdToken();
      const headers: Record<string, string> = {};
      if (token) headers.Authorization = `Bearer ${token}`;
      return { body: { ...body, messages }, headers };
    },
  }), []);

  const { messages, sendMessage, setMessages, status, stop } = useChat({
    id: sessionId,
    transport,
    onError: (err) => {
      console.error('Zen AI Widget Error:', err);
      let desc = err?.message || 'Something went wrong.';
      try {
        const parsed = JSON.parse(desc);
        if (parsed?.code === 'credits_exhausted') {
          setCreditsExhausted({
            plan: typeof parsed.plan === 'string' ? parsed.plan : 'starter',
            monthlyLimit: Number(parsed.monthlyLimit) || 3,
            errorText: parsed.error,
          });
          return;
        }
        if (parsed?.error) desc = parsed.error;
      } catch { /* use as is */ }
      toast({ title: 'Zen AI', description: desc, variant: 'destructive' });
    }
  });

  // Clear credits exhausted card when streaming resumes successfully
  React.useEffect(() => {
    if (status === 'streaming') setCreditsExhausted(null);
  }, [status]);

  const isLoading = status === 'submitted' || status === 'streaming';
  const [input, setInput] = React.useState('');

  // Handle approving proposals generated by tools (like recording sales, updating inventory)
  const handleApprove = React.useCallback(async (proposalId: string, action: any) => {
    const check = validateProposal(action, { products, customers });
    if (!check.ok) {
      toast({ title: 'Not applied', description: check.reason, variant: 'destructive' });
      return;
    }

    try {
      trackFeature('ai_proposal_approved');
      if (action.action === 'STOCK_ADJUSTMENT' || action.action === 'PRICE_CHANGE' || action.action === 'THRESHOLD_CHANGE') {
        const field = action.action === 'STOCK_ADJUSTMENT' ? 'stock'
          : action.action === 'PRICE_CHANGE' ? 'price'
          : 'lowStockThreshold';

        addToQueue({
          type: 'update-product',
          payload: { productId: action.productId, values: { [field]: action.newValue } },
        }, `Zen AI: ${action.productName} ${field} → ${action.newValue}`);
      } else if (action.action === 'LOYALTY_ADJUSTMENT') {
        addToQueue({
          type: 'update-customer',
          payload: { id: action.customerId, values: { loyaltyPoints: action.newValue } },
        }, `Zen AI: ${action.customerName} loyalty → ${action.newValue}`);
      } else if (action.action === 'RECORD_SALE') {
        const isAdmin = currentUserProfile?.role === 'admin'
          || businessData?.ownerId === currentUserProfile?.id;
        const built = buildSaleFromProposal(action, {
          products, customers, business: businessData, businessId, userId: user?.uid, isAdmin,
        });
        if (!built.ok) {
          toast({ title: 'Sale not recorded', description: built.reason, variant: 'destructive' });
          return;
        }
        addToQueue({ type: 'complete-sale', payload: built.payload }, `Zen AI: recording sale ${built.receiptNumber}`);
      }
      setProposalStatuses(prev => ({ ...prev, [proposalId]: 'APPROVED' }));
      toast({ title: 'Proposal applied', variant: 'success' });
    } catch (err: any) {
      toast({ title: 'Could not apply proposal', description: err?.message, variant: 'destructive' });
    }
  }, [products, customers, addToQueue, currentUserProfile, businessData, businessId, user?.uid, toast]);

  const handleReject = React.useCallback((proposalId: string) => {
    setProposalStatuses(prev => ({ ...prev, [proposalId]: 'REJECTED' }));
    trackFeature('ai_proposal_rejected');
  }, []);

  const handlePick = React.useCallback((text: string) => {
    sendMessage({ text });
  }, [sendMessage]);

  // Speech Recognition Setup
  React.useEffect(() => {
    if (typeof window === 'undefined') return;
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (SpeechRecognition) {
      const rec = new SpeechRecognition();
      rec.continuous = false;
      rec.interimResults = false;
      rec.lang = 'en-US';

      rec.onstart = () => {
        setIsListening(true);
      };

      rec.onresult = (event: any) => {
        const transcript = event.results[0][0].transcript;
        if (transcript) {
          setInput(prev => {
            const next = prev.trim() + ' ' + transcript.trim();
            return next.trim();
          });
        }
      };

      rec.onerror = (e: any) => {
        console.error('Speech recognition error:', e);
        setIsListening(false);
      };

      rec.onend = () => {
        setIsListening(false);
      };

      recognitionRef.current = rec;
    }
  }, []);

  const startListening = () => {
    if (recognitionRef.current && !isListening) {
      try {
        recognitionRef.current.start();
      } catch (err) {
        console.error('Failed to start speech recognition:', err);
      }
    }
  };

  const stopListening = () => {
    if (recognitionRef.current && isListening) {
      try {
        recognitionRef.current.stop();
      } catch (err) {
        console.error('Failed to stop speech recognition:', err);
      }
    }
  };

  const toggleListening = () => {
    if (isListening) {
      stopListening();
    } else {
      startListening();
    }
  };

  // Listen to dictationTrigger from layout keyboard shortcut
  React.useEffect(() => {
    if (isOpen && dictationTrigger > 0) {
      const timer = setTimeout(() => {
        startListening();
      }, 350);
      return () => clearTimeout(timer);
    }
  }, [dictationTrigger, isOpen]);

  // Scroll to bottom on new messages
  React.useEffect(() => {
    if (scrollAreaRef.current) {
      const scrollContainer = scrollAreaRef.current.querySelector('[data-radix-scroll-area-viewport]');
      if (scrollContainer) {
        scrollContainer.scrollTo({ top: scrollContainer.scrollHeight, behavior: 'smooth' });
      }
    }
  }, [messages, isLoading, creditsExhausted]);

  // Focus input when opened
  React.useEffect(() => {
    if (isOpen) {
      setTimeout(() => {
        inputRef.current?.focus();
      }, 200);
    }
  }, [isOpen]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;
    const prompt = input.trim();
    setInput('');
    sendMessage({ text: prompt });
  };

  // Stop active AI generation
  const handleStop = () => {
    try {
      stop();
    } catch (err) {
      console.error('Failed to stop AI generation:', err);
    }
  };

  // Clean and robust clear action
  const handleClear = () => {
    try {
      stop();
    } catch { /* ignore */ }
    setMessages([]);
    setProposalStatuses({});
    setCreditsExhausted(null);
    setSessionId(`session_widget_${Date.now()}`);
  };

  return (
    <>
      {/* Global CSS for the large ambient orange glow effects */}
      <style jsx global>{`
        @keyframes orange-border-glow {
          0%, 100% {
            box-shadow: 0 0 16px rgba(234, 88, 12, 0.3), 0 0 35px rgba(234, 88, 12, 0.15), inset 0 0 4px rgba(234, 88, 12, 0.05);
            border-color: rgba(234, 88, 12, 0.5);
          }
          50% {
            box-shadow: 0 0 30px rgba(234, 88, 12, 0.75), 0 0 55px rgba(249, 115, 22, 0.45), inset 0 0 8px rgba(234, 88, 12, 0.2);
            border-color: rgba(249, 115, 22, 0.7);
          }
        }
        @keyframes orange-listening-glow {
          0%, 100% {
            box-shadow: 0 0 24px rgba(234, 88, 12, 0.55), 0 0 45px rgba(234, 88, 12, 0.35);
            border-color: rgba(234, 88, 12, 0.85);
          }
          50% {
            box-shadow: 0 0 40px rgba(234, 88, 12, 0.95), 0 0 70px rgba(249, 115, 22, 0.65);
            border-color: rgba(249, 115, 22, 0.95);
          }
        }
        @keyframes orange-ai-pulse {
          0%, 100% {
            filter: drop-shadow(0 0 4px rgba(234, 88, 12, 0.5));
          }
          50% {
            filter: drop-shadow(0 0 16px rgba(234, 88, 12, 0.95)) drop-shadow(0 0 25px rgba(249, 115, 22, 0.7));
          }
        }
        .orange-glow-input {
          animation: orange-border-glow 3s infinite ease-in-out;
        }
        .orange-glow-listening {
          animation: orange-listening-glow 1.5s infinite ease-in-out;
        }
        .orange-glow-processing {
          animation: orange-ai-pulse 2s infinite ease-in-out;
        }
      `}</style>

      <AnimatePresence>
        {isOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6">
            {/* Click-away backdrop to dismiss when clicking anywhere outside */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="absolute inset-0 bg-black/40 backdrop-blur-[2px]"
              onClick={onClose}
            />

            {/* Centered Modal Content with Expandable Width & Height */}
            <motion.div
              initial={{ opacity: 0, scale: 0.96, y: 15 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.96, y: 15 }}
              transition={{ duration: 0.22, ease: 'easeOut' }}
              onClick={(e) => e.stopPropagation()}
              className={cn(
                "relative z-10 w-full flex flex-col gap-3 items-center transition-all duration-300",
                isExpanded ? "max-w-5xl" : "max-w-[680px]"
              )}
            >
              {/* Huge Soft Ambient Radial Orange Glow */}
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 h-[500px] w-[800px] max-w-none bg-[radial-gradient(circle,rgba(234,88,12,0.25)_0%,transparent_75%)] blur-[60px] pointer-events-none z-[-1]" />

              {/* Chat History Panel (Shown when messages exist or credits exhausted) */}
              <AnimatePresence>
                {(messages.length > 0 || creditsExhausted !== null) && (
                  <motion.div
                    initial={{ opacity: 0, scale: 0.95, y: 10 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95, y: 10 }}
                    className={cn(
                      "w-full bg-background/95 backdrop-blur-md border border-border/50 rounded-3xl shadow-2xl overflow-hidden flex flex-col transition-all duration-300",
                      isExpanded ? "h-[68vh]" : "h-[450px]"
                    )}
                  >
                    {/* Panel Header */}
                    <div className="flex items-center justify-between px-4 py-2.5 border-b bg-muted/20">
                      <span className="text-xs font-semibold text-muted-foreground flex items-center gap-1.5">
                        <Sparkles className="h-3.5 w-3.5 text-primary animate-pulse" />
                        Zen AI Copilot
                      </span>
                      <div className="flex items-center gap-1.5">
                        {/* Open in full dedicated page button */}
                        <Button
                          variant="ghost"
                          size="xs"
                          onClick={() => {
                            onClose();
                            router.push('/ai-insights');
                          }}
                          className="text-[11px] text-muted-foreground hover:text-foreground h-6 px-2 rounded-md gap-1"
                          title="Open in full Zen AI page"
                        >
                          <ExternalLink className="h-3 w-3" />
                          <span className="hidden sm:inline">Open in Zen AI</span>
                        </Button>

                        {/* Expand / Minimize Toggle Button */}
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => setIsExpanded(!isExpanded)}
                          className="h-6 w-6 rounded-md text-muted-foreground hover:text-foreground"
                          title={isExpanded ? "Restore standard view" : "Expand to widescreen"}
                        >
                          {isExpanded ? (
                            <Minimize2 className="h-3.5 w-3.5" />
                          ) : (
                            <Maximize2 className="h-3.5 w-3.5" />
                          )}
                        </Button>

                        {/* Clear Conversation Button */}
                        <Button
                          variant="ghost"
                          size="xs"
                          onClick={handleClear}
                          className="text-[11px] text-muted-foreground hover:text-destructive h-6 px-2 rounded-md gap-1"
                          title="Clear conversation"
                        >
                          <Trash2 className="h-3 w-3" />
                          Clear
                        </Button>
                      </div>
                    </div>

                    {/* Scrollable Message List */}
                    <ScrollArea className="flex-1 p-4" ref={scrollAreaRef}>
                      <div className="space-y-4 pb-2">
                        {messages.map((message) => {
                          const isUser = message.role === 'user';
                          const text = textOf(message);
                          const toolParts = (message.parts ?? []).filter(isToolUIPart);
                          const hasToolUI = toolParts.length > 0;

                          if (!text.trim() && !hasToolUI) return null;

                          return (
                            <div
                              key={message.id}
                              className={cn(
                                "flex items-start gap-2.5 w-full",
                                isUser ? "justify-end" : "justify-start"
                              )}
                            >
                              {!isUser && (
                                <div className="h-7 w-7 rounded-full bg-primary/10 flex items-center justify-center text-primary border border-primary/20 shrink-0 mt-0.5">
                                  <Bot className="h-4 w-4" />
                                </div>
                              )}
                              <div
                                className={cn(
                                  "flex flex-col gap-2 max-w-[88%]",
                                  isUser ? "items-end" : "items-start"
                                )}
                              >
                                {text.trim() && (
                                  <div
                                    className={cn(
                                      "rounded-2xl px-4 py-2.5 text-sm shadow-sm leading-relaxed",
                                      isUser
                                        ? "bg-primary text-primary-foreground rounded-tr-none"
                                        : "bg-muted/70 text-foreground rounded-tl-none border border-border/30"
                                    )}
                                  >
                                    {isUser ? (
                                      <p className="whitespace-pre-wrap">{text}</p>
                                    ) : (
                                      <Markdown className="text-foreground leading-relaxed">{text}</Markdown>
                                    )}
                                  </div>
                                )}

                                {/* Generative Tool Outputs & Proposals */}
                                {hasToolUI && (
                                  <div className="flex flex-col gap-2 w-full mt-1">
                                    {toolParts.map((part: any) => {
                                      const output = part.output;
                                      const isProposal = output?.type === 'PROPOSAL';
                                      const enriched = isProposal
                                        ? { ...output, status: proposalStatuses[output.proposalId] || output.status }
                                        : output;

                                      return (
                                        <div key={part.toolCallId} className="flex flex-col gap-1 w-full">
                                          {output && (
                                            <ToolResult
                                              output={enriched}
                                              onApprove={handleApprove}
                                              onReject={handleReject}
                                              onPick={handlePick}
                                            />
                                          )}
                                          {(output?.error || part.state === 'output-error') && (
                                            <div className="text-xs text-destructive bg-destructive/10 px-3 py-1.5 rounded-lg border border-destructive/20">
                                              {output?.error || part.errorText}
                                            </div>
                                          )}
                                        </div>
                                      );
                                    })}
                                  </div>
                                )}
                              </div>
                              {isUser && (
                                <div className="h-7 w-7 rounded-full bg-muted flex items-center justify-center text-muted-foreground border shrink-0 mt-0.5">
                                  <User className="h-4 w-4" />
                                </div>
                              )}
                            </div>
                          );
                        })}

                        {isLoading && (
                          <div className="flex items-start gap-2.5 w-full">
                            <div className="h-7 w-7 rounded-full bg-primary/10 flex items-center justify-center text-primary border border-primary/20 shrink-0 orange-glow-processing">
                              <Bot className="h-4 w-4" />
                            </div>
                            <div className="rounded-2xl px-4 py-3 bg-muted/50 border border-border/30 rounded-tl-none flex items-center gap-2">
                              <Loader2 className="h-4 w-4 animate-spin text-primary" />
                              <span className="text-xs text-muted-foreground">Zen AI is processing...</span>
                            </div>
                          </div>
                        )}

                        {/* Interactive Upgrade Plan Card when credits are exhausted */}
                        {creditsExhausted && (
                          <motion.div
                            initial={{ opacity: 0, y: 8, scale: 0.98 }}
                            animate={{ opacity: 1, y: 0, scale: 1 }}
                            className="w-full rounded-2xl border border-orange-500/40 bg-orange-500/10 p-4 shadow-lg flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3.5 my-2"
                          >
                            <div className="flex items-start gap-3 min-w-0">
                              <div className="h-8 w-8 rounded-full bg-orange-500/20 text-orange-500 flex items-center justify-center shrink-0 mt-0.5 border border-orange-500/30">
                                <Zap className="h-4 w-4 fill-orange-500/40" />
                              </div>
                              <div className="min-w-0">
                                <p className="text-sm font-bold text-foreground flex items-center gap-2">
                                  Monthly AI Credits Exhausted
                                  <span className="px-2 py-0.5 rounded-full text-[10px] uppercase font-semibold bg-orange-500/20 text-orange-500 border border-orange-500/30">
                                    {creditsExhausted.plan || 'Starter'}
                                  </span>
                                </p>
                                <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
                                  {creditsExhausted.errorText || `Your ${creditsExhausted.plan || 'current'} plan includes ${creditsExhausted.monthlyLimit.toLocaleString()} credits a month, and it is spent. Upgrade to Pro or Enterprise for higher limits and unlimited features.`}
                                </p>
                              </div>
                            </div>

                            <div className="flex items-center gap-2 shrink-0 self-end sm:self-center">
                              <Button
                                onClick={() => {
                                  onClose();
                                  router.push('/billing');
                                }}
                                className="bg-orange-600 hover:bg-orange-700 text-white shadow-md text-xs font-semibold px-4 py-2 h-8.5 rounded-xl flex items-center gap-1.5 cursor-pointer"
                              >
                                <Zap className="h-3.5 w-3.5 fill-current" />
                                Upgrade Plan
                              </Button>
                            </div>
                          </motion.div>
                        )}
                      </div>
                    </ScrollArea>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Pill Input Container */}
              <div
                className={cn(
                  "w-full flex items-center bg-background border rounded-full pl-3 pr-2 py-2 border-border/80 shadow-2xl transition-all duration-300",
                  isListening ? "orange-glow-listening scale-[1.01]" : "orange-glow-input"
                )}
              >
                {/* Dictation Microphone Toggle Button on left */}
                <button
                  type="button"
                  onClick={toggleListening}
                  className={cn(
                    "p-2 rounded-full transition-all duration-200 mr-2 shrink-0 flex items-center justify-center relative",
                    isListening
                      ? "bg-[#ea580c]/15 text-[#ea580c] animate-pulse"
                      : "hover:bg-muted text-muted-foreground hover:text-foreground"
                  )}
                  title={isListening ? "Stop listening" : "Start voice dictation (or press Ctrl)"}
                >
                  {isListening ? (
                    <Mic className="h-5.5 w-5.5 animate-bounce" />
                  ) : (
                    <Mic className="h-5.5 w-5.5" />
                  )}
                  {isListening && (
                    <span className="absolute -top-1 -right-1 flex h-2 w-2">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-orange-400 opacity-75"></span>
                      <span className="relative inline-flex rounded-full h-2 w-2 bg-orange-500"></span>
                    </span>
                  )}
                </button>

                {/* Text input & Send/Stop actions */}
                <form onSubmit={handleSubmit} className="flex-1 min-w-0 flex items-center gap-2">
                  <input
                    ref={inputRef}
                    type="text"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    placeholder={isListening ? "Listening... Speak now..." : "Ask Zen AI... (or press Ctrl to talk)"}
                    disabled={isLoading}
                    className="flex-1 min-w-0 bg-transparent border-0 text-sm focus:outline-none focus:ring-0 focus:border-0 py-1 pl-1"
                  />

                  {/* Action Buttons: Submit Arrow or Stop Button when active */}
                  <div className="flex items-center gap-2 shrink-0">
                    {isLoading ? (
                      <Button
                        type="button"
                        size="icon"
                        onClick={handleStop}
                        className="h-10 w-10 rounded-full transition-all flex items-center justify-center shrink-0 border-0 shadow-md bg-[#ea580c] hover:bg-[#ea580c]/90 text-white cursor-pointer animate-pulse"
                        title="Stop generation"
                      >
                        <Square className="h-4.5 w-4.5 fill-current" />
                      </Button>
                    ) : (
                      <Button
                        type="submit"
                        size="icon"
                        disabled={!input.trim()}
                        className={cn(
                          "h-10 w-10 rounded-full transition-all flex items-center justify-center shrink-0 border-0 shadow-sm",
                          input.trim()
                            ? "bg-[#ea580c] hover:bg-[#ea580c]/90 text-white shadow-md cursor-pointer"
                            : "bg-[#ea580c]/20 text-[#ea580c]/80 cursor-not-allowed"
                        )}
                        title="Send prompt"
                      >
                        <ArrowUp className="h-5.5 w-5.5 stroke-[2.75]" />
                      </Button>
                    )}

                    <Button
                      type="button"
                      variant="ghost"
                      size="icon"
                      onClick={onClose}
                      className="h-10 w-10 rounded-full text-muted-foreground hover:bg-muted hover:text-foreground flex items-center justify-center shrink-0"
                      title="Close"
                    >
                      <X className="h-5 w-5" />
                    </Button>
                  </div>
                </form>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </>
  );
}
